### ISSUE TITLE
Issue with Donorbox embed

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org#156] opened 2024-10-07 03:59 UTC
Issue:

Cannot make a donation via credit card because the entire form is not visible. This happens on both desktop and mobile. The form itself is not scrollable (either before or after filling in card info), so there's no way for a prospective donor to submit a credit card donation. 

![image](https://github.com/user-attachments/assets/0944c606-ab4c-48aa-8faf-f3e74fcc78f4)

The same issue appears to affect bank transfers as well.

![image](https://github.com/user-attachments/assets/467ab56b-e695-490a-aea5-85fc610c2b20)

Fix.

**Comment by taoeffect** [comment] 2024-10-07 04:05
@SebinSong I've assigned this to you.

Unless there's an obvious easy fix to this, feel free to just replace the entire form with a button like the donorbox button here: https://okturtles.org/donate/

**Comment by SebinSong** [comment] 2024-10-08 00:53
@taoeffect The cause of the issue is `height="550px"` attribute specified on the `<iframe/>` element.

https://github.com/okTurtles/groupincome.org/blob/a90f709168e934021d5982615e2f2fcc807e8a8d/src/pages/donate.astro#L34

And any attempts to change the height to something like `max-content` via either inline attribute or css don't work apparently because `<iframe />` tag doesn't have the ability to adjust its own dimension based on the content.

There is actually various solutions suggested out there where we calculate/use the `scrollHeight` property of the root document element within the `<iframe/>` once `load` event is fired on it. (reference: https://www.tutorialspoint.com/how-to-adjust-the-width-and-height-of-an-iframe-to-fit-with-content-in-it-html)

But this kind of solution is **not** applicable to our case here because accessing the DOM within this donorbox widget from any cross-origin is blocked (screenshot below)

<img width="621" alt="iframe-cors-error" src="https://github.com/user-attachments/assets/56e5a65e-3f40-41e9-a794-386d0067ddac">

which makes sense as it's payment-related.
In the screenshot, it's `localhost` but I believe the same issue will happen from our PROD website too.

For this reason, I will make a fix with this alternative approach you suggested above:

> Unless there's an obvious easy fix to this, feel free to just replace the entire form with a button like the donorbox button here: https://okturtles.org/donate/

Thanks,

**Closed as completed** 2024-10-08 23:12 UTC
Labels: bug, priority:high
